workflows:
  default:
    name: Build and Upload APK
    scripts:
      - name: Install dependencies
        script: |
          # You can install any dependencies needed by your app
          chmod +x gradlew  # Make gradlew executable (if not already)
      - name: Build APK
        script: |
          ./gradlew assembleRelease  # This will build the release APK
    artifacts:
      - build/app/outputs/apk/release/app-release.apk  # Path to your APK after the build
    